### ISSUE TITLE
stripGenericArgumentsFromCode function (used in the Spacing Module) doesn't handle multiple generic arguments/parameters

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeStyleGradingAid#15]
Test case: P2, juang905
Look for `Map<Integer, Element>`.

Works only on things like `ArrayList<Element>`

**Comment by msimmon6** [comment]
I feel like you may be able to use regex for a comma-delimited thing between < and > and to ignore that case. However, this would cause something like bool b = Foo<Bool, Bool>3; where Foo and Bool are variables (and there are more issues if they're starting variables with capital letters).

UPDATE: Apparently comma is not an operator in Java, so that case is illegal. I feel like this if(regex on the line is true) then do nothing case works fine in my head.

**Comment by Algomorph** [comment]
I've just revamped the spacing module to use the parser (#24), so this should no longer be an issue after that PR is merged.
